**Оценка модели регрессии. Прогноз января 2026 г.**

In [1]:
%cd D:\Python_2\MLogic_project\Yuperio\prognoz_prodaj_12_2025

D:\Python_2\MLogic_project\Yuperio\prognoz_prodaj_12_2025

In [7]:
import pandas as pd
import numpy as np

from utils import evaluate_model

In [3]:
df_sale_true = pd.read_csv('etl/sale_01_2026.csv')
df_csv = df_sale_true[(df_sale_true['exit_type']=='Продажа') & (df_sale_true['Territory'].str.contains('moscow', case=False, na=False)) ]
df_sale_true

,location_mdlp_id,Адрес ЛПУ,Territory,exit_type,2026-01-01
0,166,"Москва г, Митинский 3-й пер., 4",MR PC BU CVM Moscow_3,Продажа,24.0
1,167,"Серпухов г, Московское ш., 64",MR PC BU CVM Moscow_11,Продажа,8.0
2,169,"Москва г, Маршала Федоренко ул., 6",MR PC BU CVM Moscow_SAO,Продажа,19.0
3,170,"Москва г, Скульптора Мухиной ул., 14",MR PC BU CVM Moscow_2,Продажа,14.0
4,171,"Москва г, Героев Панфиловцев ул., 8",MR PC BU CVM Moscow_3,Продажа,3.0
...,...,...,...,...,...
72649,592129,НЕТ ДАННЫХ,НЕТ ДАННЫХ,Продажа,NaN
72650,592146,НЕТ ДАННЫХ,НЕТ ДАННЫХ,Продажа,1.0
72651,592148,НЕТ ДАННЫХ,НЕТ ДАННЫХ,Продажа,NaN
72652,592155,НЕТ ДАННЫХ,НЕТ ДАННЫХ,Продажа,NaN
72653,592160,НЕТ ДАННЫХ,НЕТ ДАННЫХ,Продажа,1.0

In [4]:
df_sale_predict = pd.read_csv('result_predict.csv')
df_sale_predict

      mdlp_id  sale
0         166    23
1         167     4
2         168     1
3         169    24
4         170    14
...       ...   ...
6888   535646     4
6889   535785     2
6890   535786     3
6891   535826     4
6892   535827     3

[6893 rows x 2 columns]

In [5]:
de_merge = pd.merge(
    df_sale_true,
    df_sale_predict,
    left_on='location_mdlp_id',
    right_on='mdlp_id',
    how='inner'  # inner join (только совпадающие записи)
)

de_merge = de_merge[['mdlp_id', '2026-01-01', 'sale']]
de_merge = de_merge.rename(columns={'2026-01-01': 'fact', 'sale': 'predict'})
de_merge = de_merge.fillna(0)
de_merge

      mdlp_id  fact  predict
0         166  24.0       23
1         167   8.0        4
2         169  19.0       24
3         170  14.0       14
4         171   3.0        2
...       ...   ...      ...
5521   535646   5.0        4
5522   535785   0.0        2
5523   535786   4.0        3
5524   535826   2.0        4
5525   535827   3.0        3

[5526 rows x 3 columns]

In [8]:
fact = de_merge['fact'].to_list()
predict = de_merge['predict'].to_list()

evaluate_model(fact, predict, 'LightGBM')

LightGBM Результаты:
Среднеквадратичная ошибка (MSE): 66.1321
Корень из MSE (RMSE): 8.1322
Средняя абсолютная ошибка (MAE): 3.5610
Средняя абсолютная процентная ошибка (SMAPE): 72.73%
Коэффициент детерминации (R²): 0.3686

{'MSE': 66.13210278682591,
 'RMSE': np.float64(8.132164704851096),
 'MAE': 3.5609844372059354,
 'R2': 0.3686425422270795}